name = "LockedStructs"
uuid = "e5c420f2-43f0-480f-8837-085dee2eff6d"
authors = ["AstroFloof <does.not.kompute@gmail.com>"]
version = "0.1.1"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
